name: snug_logger
description: Snug Logger - Cozy, Fun, Powerful! Elevate your coding with simplicity and a touch of fun. Logging made delightful.
version: 1.0.9
homepage: https://github.com/wmtrnsapanzaveri/snug_logger
repository: https://github.com/wmtrnsapanzaveri/snug_logger

environment:
  sdk: ">=2.16.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0


dev_dependencies:

  lints: ^4.0.0
  test: ^1.25.8
