name: snug_logger
description: Elevate your Flutter app's logging experience with snug_logger – the cozy companion for developers who value simplicity, performance, and a touch of fun! This logging package goes beyond the ordinary, offering an intuitive API, customization options, and a lightweight footprint.
version: 1.0.0
homepage: https://github.com/wmtrnsapanzaveri/snug_logger
repository: https://github.com/wmtrnsapanzaveri/snug_logger

environment:
  sdk: ^3.2.5

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0


dev_dependencies:

  lints: ^2.1.0
  test: ^1.24.0
