name: snug_logger
description: Snug Logger - Cozy, Fun, Powerful! Elevate your coding with simplicity and a touch of fun. Logging made delightful.
version: 1.0.3
homepage: https://github.com/wmtrnsapanzaveri/snug_logger
repository: https://github.com/wmtrnsapanzaveri/snug_logger

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0


dev_dependencies:

  lints: ^3.0.0
  test: ^1.24.0
