name: snug_logger
description: Snug Logger - Cozy, Fun, Powerful! Elevate your coding with simplicity and a touch of fun. Logging made delightful.
version: 1.0.7
homepage: https://github.com/wmtrnsapanzaveri/snug_logger
repository: https://github.com/wmtrnsapanzaveri/snug_logger

environment:
  sdk: ">=2.16.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  dio: ^5.4.0


dev_dependencies:

  lints: ^3.0.0
  test: ^1.24.0
