name: Update Diagrams

on:
  push:
    paths:
      - '**/*.md'  # Adjust the path to your Markdown files containing Mermaid diagrams

jobs:
  render-diagrams:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Render Mermaid diagrams
        uses: nielsvaneck/render-md-mermaid@v2

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Update rendered Mermaid diagrams'
          file_pattern: '*.svg'
